---
- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog or is installed"
  apt:
      name: rsyslog
      state: present
      install_recommends: false
  when:
      - ubuntu2004cis_rule_4_2_1_1
      - ubuntu2004cis_syslog == "rsyslog"
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.1.1

- name: "SCORED | 4.2.1.2 | PATCH | Ensure rsyslog Service is enabled"
  service:
      name: rsyslog
      enabled: yes
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_2
      - ubuntu2004cis_syslog == "rsyslog"
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.1.2

- name: "NOTSCORED | 4.2.1.3 | PATCH | Ensure logging is configured"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_3
  tags:
      - level1
      - notscored
      - patch
      - syslog
      - rule_4.2.1.3
      - notimplemented

- name: "SCORED | 4.2.1.4 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  when:
      - ubuntu2004cis_rule_4_2_1_4
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.1.4

- name: "SCORED | 4.2.1.5 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_5
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.1.5
      - notimplemented

- name: "NOTSCORED | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_6
  tags:
      - level1
      - notscored
      - patch
      - syslog
      - rule_4.2.1.6
      - notimplemented

- name: "SCORED | 4.2.2.1 | PATCH | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?ForwardToSyslog=(yes|no)"
    line: ForwardToSyslog=yes
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_2_1
  notify:
    - restart journald
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.2.1

- name: "SCORED | 4.2.2.2 | PATCH | Ensure journald is configured to compress large log files"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Compress=(yes|no)"
    line: Compress=yes
  when:
      - ubuntu2004cis_rule_4_2_2_2
  notify:
    - restart journald
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.2.2

- name: "SCORED | 4.2.2.3 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Storage=(auto|persistent)"
    line: Storage=persistent
  when:
      - ubuntu2004cis_rule_4_2_2_3
  notify:
    - restart journald
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.2.3

- name: "SCORED | 4.2.3 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: false
  failed_when: false
  when:
      - ubuntu2004cis_rule_4_2_3
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.2.3

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  block:
      - name: "NOTSCORED | 4.3 | PATCH | Register logrotate.d files"
        find:
            paths: /etc/logrotate.d/
        register: log_rotates

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate.conf exists"
        file:
            path: /etc/logrotate.conf
            state: touch
        changed_when: false

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
        replace:
            path: "{{ item.path }}"
            regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
            replace: "\\1{{ ubuntu2004cis_logrotate }}"
        with_items:
            - "{{ log_rotates.files }}"
            - { path: "/etc/logrotate.conf" }
  when:
      - ubuntu2004cis_rule_4_3
  tags:
      - level1
      - notscored
      - patch
      - syslog
      - rule_4.3

- name: "SCORED | 4.4 | PATCH | Ensure logrotate assigns appropriate permissions"
  lineinfile:
      state: present
      dest: /etc/logrotate.conf
      regexp: '^create'
      line: 'create 0640'
  when:
      - ubuntu2004cis_rule_4_4
  tags:
      - level1
      - scored
      - patch
      - syslog
      - rule_4.4
